config/routes.rb
Rails.application.routes.draw do
  get 'books/index'

  resources :books 
  resources :authors

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :description, presence: true
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end


  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @author = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :description, :page_count)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_form.html.erb
<%= form_with model: @author, local: true do |form| %>

<% if @author.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@author.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Welcome to Richmond Library</h1>
<%= link_to 'Richmond Library Books', controller: 'books' %>

<%= link_to 'New Author', new_author_path %>

<%= link_to 'New Book', new_book_path %>


<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th colspan="5"></th>
    <th></th>
  </tr>

  <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name %></td>
      <td><%= author.last_name %></td>
      <td><%= link_to 'Show', author_path(author) %></td>
      <td><%= link_to 'Edit', edit_author_path(author) %></td>
      <td><%= link_to 'Destroy', author_path(author),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @author.last_name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@book.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :page_count %><br>
    <%= form.text_area :page_count %>
  </p>

  <%= collection_select(:book, :author_id, Author.all, :id, :full_name, options ={:prompt => "-Select a Author"})%>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Welcome to Richmond Library</h1>
<%= link_to 'Richmond Library Authors', controller: 'authors' %>

<%= link_to 'New Book', new_book_path %>

<%= link_to 'New Author', new_author_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Page Count</th>
    <th>Author</th>
    <th colspan="5"></th>
    <th></th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.description %></td>
      <td><%= book.page_count %></td>
      <td><%= book.author.first_name %> <%= book.author.last_name %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Page Count:</strong>
  <%= @book.page_count %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RichmondLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>